apiVersion: apps/v1
kind: Deployment
metadata:
  name: conduit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conduit-app
  template:
    metadata:
      labels:
        app: conduit-app
    spec:
      containers:
      - name: conduit-app
        image: conduitacr.azurecr.io/conduit-app:latest
        ports:
        - containerPort: 4321 # Updated to match the internal container port
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: conduit-service
spec:
  type: LoadBalancer
  selector:
    app: conduit-app
  ports:
  - protocol: TCP
    port: 80       # External port for accessing the app
    targetPort: 4321 # Matches the containerPort inside the pod
