apiVersion: apps/v1
kind: Deployment
metadata:
  name: conduit-app
  namespace: dev # Replace with 'staging' or 'production' for other environments
spec:
  replicas: 2 # Default starting replicas
  revisionHistoryLimit: 5 # Retain the last 5 revisions
  selector:
    matchLabels:
      app: conduit-app
  template:
    metadata:
      labels:
        app: conduit-app
    spec:
      containers:
      - name: conduit-app
        image: conduitacr.azurecr.io/conduit-app:latest
        ports:
        - containerPort: 4321
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
#        livenessProbe: # Health check for pod liveness
#          httpGet:
#            path: /health
#            port: 4321
#          initialDelaySeconds: 5
#          periodSeconds: 10
#        readinessProbe: # Health check for pod readiness
#          httpGet:
#            path: /ready
#            port: 4321
#          initialDelaySeconds: 5
#          periodSeconds: 10
      imagePullSecrets:
      - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: conduit-service
  namespace: dev # Replace with 'staging' or 'production' for other environments
spec:
  type: LoadBalancer
  selector:
    app: conduit-app
  ports:
  - protocol: TCP
    port: 80       # External port for accessing the app
    targetPort: 4321 # Matches the containerPort inside the pod

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: conduit-hpa
  namespace: dev # Replace with 'staging' or 'production' for other environments
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: conduit-app
  minReplicas: 1 # Start with 1 replica in dev
  maxReplicas: 5 # Scale up to 5 replicas for dev
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # Lower utilization target for dev
