name: CD Pipeline with Rollback

on:
  push:
    branches:
      - main
      - release/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Set up AKS credentials
    - name: Set up AKS credentials
      run: |
        az aks get-credentials --resource-group ConduitResourceGroup --name ConduitAKS

    # Step 4: Build and push Docker image to ACR
    - name: Build and push Docker image
      run: |
        az acr login --name conduitacr
        docker build -t conduitacr.azurecr.io/conduit-app:${{ github.sha }} .
        docker push conduitacr.azurecr.io/conduit-app:${{ github.sha }}

    # Step 5: Deploy to AKS with change tracking
    - name: Deploy to AKS
      id: deploy
      run: |
        kubectl set image deployment/conduit-app conduit-app=conduitacr.azurecr.io/conduit-app:${{ github.sha }} --record

    # Step 6: Verify Deployment Success
    - name: Verify deployment status
      id: verify
      run: |
        kubectl rollout status deployment conduit-app --timeout=180s
      continue-on-error: true

    # Step 7: Log Failure and Rollback on Deployment Failure
    - name: Log deployment failure
      if: failure() && steps.verify.outcome == 'failure'
      run: |
        echo "Deployment verification failed. Initiating rollback."
        exit 1

    - name: Rollback Deployment
      if: failure() && steps.verify.outcome == 'failure'
      run: |
        echo "Rolling back to the previous stable version..."
        kubectl rollout undo deployment conduit-app
        echo "Rollback complete. The application is now running the previous stable version."

    # Step 8: Final Status
    - name: Mark workflow as failed if rollback occurred
      if: failure() && steps.verify.outcome == 'failure'
      run: |
        echo "Workflow completed with rollback due to deployment failure."
        exit 1

